name: Compile LaTeX with Caching

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: step-security/harden-runner@446798f8213ac2e75931c1b0769676d927801858 # v2.10.0
      with:
        egress-policy: audit
    - name: run pwd
      run: pwd
    - name: pwd2 
      run: pwd 
  run:
    runs-on: ubuntu-latest

    steps:
    - name: run ls 
      run: ls
      

