name: Compile LaTeX with Bibliography

on:
  push:
    branches:
      - main  
      - master
  pull_request:  # Trigger on pull request
jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: echo step
      run: echo "Hello from self-hosted runner"

    - name: Create a new issue 
      uses: rof13thfloor/create-an-issue@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
